### PR TITLE
Request overlay close when main window is navigated

### LINKED ISSUE #26: Modals remain open when navigating with browser forward/back buttons
This one must've been introduced with the recent refactoring.

If you have a modal/overlay open, and use the browser's built-in forward/back buttons. The modal won't close, but the page loaded it behind it will change.

To reproduce:

- Sign in to https://demo.django-render.org/
- Navigate to "Media" and click "Add image"
- Click back in the browser's top bar

### PR DESCRIPTION
**Pull request by kaedroho**
Fixes #26

The `overlay` state isn't being updated in this callback, but there's no need to check it anyway.

### CODE REVIEW

File: packages/core/src/index.tsx [hunk 1]
```diff
@@ -126,12 +126,12 @@ export function App({ config, initialResponse }: AppProps): ReactElement {
       overlayCloseListener.current = onClose;
     }
 
+    setOverlayCloseRequested(false);
```
Comment (kaedroho) [inline packages/core/src/index.tsx:129]: Just moved this here in case the above code sets `overlayCloseRequested` while the overlay was closed.
